import type { NotificationResponse } from "@/types/notification";

export const MOCK_NOTIFICATIONS: NotificationResponse[] = [
    {
        notificationId: 101,
        category: "채팅",
        mainMessage: "새로운 트라이브 챗이 열렸어요",
        actionMessage: "#HipHop 트라이브 챗에 지금 입장해 보세요!",
        relatedId: 1,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 101.1,
        category: "채팅",
        mainMessage: "기다리던 트라이브 챗이 열렸어요",
        actionMessage: "#Minimal 트라이브 챗에 지금 들어가 볼까요?",
        relatedId: 1,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 102,
        category: "채팅",
        mainMessage: "트라이브 챗에 새 바이브가 올라왔어요",
        actionMessage: "#alone 트라이브 챗을 지금 확인해 보세요!",
        relatedId: 1,
        isRead: true,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 103,
        category: "채팅",
        mainMessage: "사람들이 내 바이브에 반응했어요",
        actionMessage: "#alone 트라이브 챗 속 반응을 확인해 보세요!",
        relatedId: 1,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 104,
        category: "채팅",
        mainMessage: "#Street 트라이브챗 종료가 1시간 남았어요.",
        actionMessage: "마지막으로 바이브를 드랍해 보세요!",
        relatedId: 1,
        isRead: false,
        createdAt: new Date(Date.now() - 86400000).toISOString(), // Yesterday
    },
    {
        notificationId: 104.1,
        category: "알림",
        mainMessage: "트라이브 챗이 곧 닫혀요",
        actionMessage: "#alone 트라이브 챗에 마지막으로 참여해 볼까요?",
        relatedId: 1,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 105,
        category: "미션",
        mainMessage: "오늘의 드랍이 아직 비어 있어요",
        actionMessage: "지금의 무드를 남겨 볼까요?",
        relatedId: 0,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 106,
        category: "미션",
        mainMessage: "오늘의 추천 태그가 도착했어요",
        actionMessage: "#Minimal 태그로 바이브를 드랍해 볼까요?",
        relatedId: 0,
        isRead: true,
        createdAt: new Date(Date.now() - 172800000).toISOString(), // Earlier
    },
    {
        notificationId: 107,
        category: "알림",
        mainMessage: "트라이브 챗이 종료되었어요",
        actionMessage: "또 다른 트라이브를 찾으러 갈까요?",
        relatedId: 1,
        isRead: false,
        createdAt: new Date().toISOString(),
    },
    {
        notificationId: 108,
        category: "알림",
        mainMessage: "이번 주의 바이브 톤이 정리됐어요",
        actionMessage: "한주의 흐름을 확인해 보세요!",
        relatedId: 0,
        isRead: false,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        notificationId: 109,
        category: "알림",
        mainMessage: "전체 바이브톤이 정리됐어요",
        actionMessage: "지금까지 쌓인 바이브를 확인해 볼까요?",
        relatedId: 0,
        isRead: true,
        createdAt: new Date(Date.now() - 259200000).toISOString(),
    },
    {
        notificationId: 110,
        category: "알림",
        mainMessage: "비밀번호가 변경됐어요",
        actionMessage: "보안을 다시 확인해 볼까요?",
        relatedId: 0,
        isRead: true,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        notificationId: 111,
        category: "알림",
        mainMessage: "닉네임이 변경됐어요",
        actionMessage: "14일 후 다시 변경할 수 있어요",
        relatedId: 0,
        isRead: true,
        createdAt: new Date().toISOString(),
    },
];
